services:
  ro5_api:
    restart: unless-stopped
    build:
      context: ./app
    environment:
      - APP_PORT=${APP_PORT}
    env_file:
      - .env
    volumes:
      - static_files_flasgger:/app/flasgger_static/
    ports:
      - "127.0.0.1:${APP_PORT:-8002}:${APP_PORT:-8002}"
    networks:
      - ro5_net

  ro5_ui:
    restart: "no"
    build:
      context: https://github.com/unmtransinfo/Ro5-UI.git#deploy-prod-16
    env_file:
      - .env
    command: sh -c "npm install && npx vite build && mkdir -p /app/dist-out && cp -r dist/. /app/dist-out/"
    volumes:
      - /var/www/ro5:/app/dist-out
    networks:
      - ro5_net

volumes:
  static_files_flasgger:

networks:
  ro5_net: